Improwised/go-scrapper

main.go
Asana Task[#1200145374025856](https://app.asana.com/0/630636295096259/1200145374025856)
Renamed response_bytes to downloader/response_bytes in meta file.
Renamed request_count to downloader/request_count in meta file.
fixed condition for reviewstatus.
=> fixed no_review status

main.go
scrap non recommended reviews when total count is zero
=> scrap non recommended reviews when total count is zero

main.go
=> Add retry functionality

main.go
=> Fixed deadlock issue by allowed different domains

main.go
=> scraped all the previous reviews

main.go
Retry request if miss some data in response
=> Retry request if miss some data in response

main.go
Fixed  scrapy status.
Added delay at retry time.
=> Fixed scraped status

main.go
=> Remove time delay

main.go
[#1200371111212581](https://app.asana.com/0/630636295096259/1200371111212581)
Override default timeout of request.
retry request when business id missed.
=> add custome timeout and retry request wheb business id is none

main.go
[#1200371111212581](https://app.asana.com/0/630636295096259/1200371111212581)
Added status page_format_change, when business id missed.
=> added format changed status when businees id missed

main.go
[#1200371111212581](https://app.asana.com/0/630636295096259/1200371111212581)
Retry request when business id missed
=> Retry request when business id missed

main.go
Decreased delay between request
=> Decreased delay between request

main.go
=> decreased timeout and delay

main.go
=> revert timeout changes

main.go
=> Used direct service url

main.go
=> Fixed errors

main.go
Filter out compare target uaing isAd key
=> Filter out compare target uaing isAd key

main.go
Set meta file for search result
=> Set meta file for search result

main.go
=> Add some log

main.go
=> Changed position of log

main.go
=> Fixed last_review bug

main.go
code update to get business id
=> business id get code is updated

main.go
=>  update code to get histogram

main.go
update histogram functionality and and go-colly wait function for normal review
=> Use go-colly wait function

main.go
update histogram functionality and and go-colly wait function for normal review
=> Use go-colly collector's wait function

main.go
Remove extrenal wait group and use insternal go-colly waitgroup
=> remove external waitgroup and use inster colly wat group

main.go
Change match url from local to business
=> change match url from local to business

collyfunc/collector.go, main.go, utils/utils.go
Remove external wait group and use internal go-colly wait-group
=> yelp-go scrapper code refactor 1

main.go
=> update match url

main.go
handle search urls which doesn't have business_id
=> handle search url  which doen't have business_id

collyfunc/collyfunc.go, main.go
Asana Task:[1200145374025856](https://app.asana.com/0/630636295096259/1200145374025856)
1. made separation in collector one for profile other for review and configuration
=> made separation in collector one for profile other for review
